config: default
use_gpu: true

log:
  log_freq: 10
  save_freq: 100

data:
  root: ./data/birds/
  extensions:
    - .jpg
    - .jpeg
    - .png

img:
  size: 128
  channels: 3

optim:
  batch_size: 64
  dis_iters_per_gen_iter: 2
  gen:
    lr: 0.0002
    betas: [0.5, 0.999]
    weight_decay: 0.001
  dis:
    lr: 0.0002
    betas: [0.5, 0.999]
    weight_decay: 0.001

arch:
  gen:
    z: 64
    width: 32
  dis:
    width: 32
