config: spatial-encoding
use_gpu: true

log:
  log_freq: 10
  save_freq: 100

data:
  root: ./data/birds/
  extensions:
    - .jpg
    - .jpeg
    - .png

img:
  size: 128
  channels: 3

optim:
  batch_size: 16
  dis_iters_per_gen_iter: 1
  gen:
    lr: 0.0002
    betas: [0.5, 0.999]
    weight_decay: 0.0
    ema_alpha: 0.0
  dis:
    lr: 0.0002
    betas: [0.5, 0.999]
    weight_decay: 0.001

wandb:
  enable: false
  project: zgan
  group: birds
  tags: [birds, 3x128x128]
  log_frequency: 10

arch:
  gen:
    context:
      z: 256
      w: 64  # Network width multiplier
    layers:
      # Block 1: z x 1 x 1
      - type: ConvTranspose2d
        args: [z, w*16, 8, 1, 0]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 2: w*16 x 8 x 8
      - type: SpatialEncoding
        args: [2]
        kwargs: {}
      - type: Conv2d
        args: [w*16+4, w*8, 3, 1, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [w*8]
        kwargs: {}
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      - type: ConvTranspose2d
        args: [w*8, w*8, 2, 2, 0]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 3: w*8 x 16 x 16
      - type: SpatialEncoding
        args: [3]
        kwargs: {}
      - type: Conv2d
        args: [w*8+6, w*4, 3, 1, 1]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      - type: ConvTranspose2d
        args: [w*4, w*4, 2, 2, 0]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 4: w*4 x 32 x 32
      - type: SpatialEncoding
        args: [4]
        kwargs: {}
      - type: Conv2d
        args: [w*4+8, w*2, 3, 1, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [w*2]
        kwargs: {}
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      - type: ConvTranspose2d
        args: [w*2, w*2, 2, 2, 0]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 5: w*2 x 64 x 64
      - type: SpatialEncoding
        args: [5]
        kwargs: {}
      - type: Conv2d
        args: [w*2+10, w*1, 3, 1, 1]
        kwargs: { bias: true }
      - type: BatchNorm2d
        args: [w*1]
        kwargs: {}
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      - type: ConvTranspose2d
        args: [w*1, w*1, 2, 2, 0]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 6: w*1 x 128 x 128
      - type: Conv2d
        args: [w*1, w*1, 3, 1, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [w*1]
        kwargs: {}
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      # Block 7: w*1 x 128 x 128
      - type: Conv2d
        args: [w*1, w*1, 3, 1, 1]
        kwargs: { bias: true }
      - type: ReLU
        args: []
        kwargs: { inplace: true }
      - type: Conv2d
        args: [w*1, 3, 1, 1, 0]
        kwargs: { bias: true }
      - type: Sigmoid
        args: []
        kwargs: {}

  dis:
    context: {}
    layers:
      - type: RandomHorizontalFlip
        args: []
        kwargs: {}
      # Block 1: 3 x 128 x 128
      - type: Conv2d
        args: [3, 32, 5, 2, 2]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [32]
        kwargs: {}
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 2: 32 x 64 x 64
      - type: Conv2d
        args: [32, 64, 5, 2, 2]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [64]
        kwargs: {}
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 3: 64 x 32 x 32
      - type: Conv2d
        args: [64, 128, 3, 2, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [128]
        kwargs: {}
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 4: 128 x 16 x 16
      - type: Conv2d
        args: [128, 256, 3, 2, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [256]
        kwargs: {}
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 5: 256 x 8 x 8
      - type: Conv2d
        args: [256, 512, 3, 2, 1]
        kwargs: { bias: false }
      - type: BatchNorm2d
        args: [512]
        kwargs: {}
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 6: 512 x 4 x 4
      - type: Conv2d
        args: [512, 1024, 4, 1, 0]
        kwargs: { bias: true }
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 6: 1024 x 1 x 1
      - type: Conv2d
        args: [1024, 256, 1, 1, 0]
        kwargs: { bias: true }
      - type: LeakyReLU
        args: [0.2]
        kwargs: { inplace: true }
      # Block 7: 256 x 1 x 1
      - type: Conv2d
        args: [256, 1, 1, 1, 0]
        kwargs: { bias: true }
      - type: Sigmoid
        args: []
        kwargs: {}
